# This workflow will validate a golang project

name: Validate

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3

    - name: Set up Python
      uses: actions/setup-python@v3

    - name: Install staticcheck
      run: "go install 'honnef.co/go/tools/cmd/staticcheck@latest'"

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
