# This workflow will validate a golang project

name: Validate

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3

    - run: "go vet ./..."

    - uses: dominikh/staticcheck-action@v1.3.0
      with:
        install-go: false
